[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "credentialless"
    Cross-Origin-Opener-Policy = "same-origin"

# [[redirects]]
#   from = "/*"
#   to = "451.html"
#   status = 451
#   force = true
#   conditions = {Country=["BY","CU","IR","IQ","CI","LR","KP","RU","SD","SY","US","ZW"]}

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200

[[plugins]]
  package = "/plugins/netlify/env"
  [plugins.inputs]
      source = '_redirects'
      base = '/opt/build/repo/public'

[context.production.environment]
  REACT_APP_CONFIG="prod"
  REACT_APP_RESTRICTED_COUNTRIES = "AE"
  REACT_APP_LOCK_TIMEOUT = "900000"
  # REACT_APP_RESTRICTED_COUNTRIES = "BY,CU,IR,IQ,CI,LR,KP,RU,SD,SY,US,ZW"

[context.staging.environment]
  REACT_APP_CONFIG="dev"
  REACT_APP_RESTRICTED_COUNTRIES = "AE"
  REACT_APP_LOCK_TIMEOUT = "300000"
  # REACT_APP_RESTRICTED_COUNTRIES = "BY,CU,IR,IQ,CI,LR,KP,RU,SD,SY,US,ZW"
