[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "credentialless"
    Cross-Origin-Opener-Policy = "same-origin"

# [[redirects]]
#   from = "/*"
#   to = "451.html"
#   status = 451
#   force = true
#   conditions = {Country=["BY","CU","IR","IQ","CI","LR","KP","RU","SD","SY","US","ZW"]}

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200

[[plugins]]
  package = "/plugins/netlify/env"
  [plugins.inputs]
      source = '_redirects'
      base = '/opt/build/repo/public'

[context.production.environment]
  REACT_APP_EXPLORER_ADDRESS_TEMPLATE = "https://polygonscan.com/address/%s"
  REACT_APP_EXPLORER_TX_TEMPLATE = "https://polygonscan.com/tx/%s"
  REACT_APP_EXPLORER_URL = "https://polygonscan.com"
  REACT_APP_NETWORK = "137"
  REACT_APP_CONTRACT_ADDRESS = "0x72e6B59D4a90ab232e55D4BB7ed2dD17494D62fB"
  REACT_APP_TOKEN_ADDRESS = "0xB0B195aEFA3650A6908f15CdaC7D92F8a5791B0B"
  REACT_APP_RELAYER_URL = "https://relayer-mvp.zkbob.com"
  REACT_APP_PROVER_URL = "https://remoteprover-mvp.zkbob.com/"
  REACT_APP_RPC_URL = "https://polygon-rpc.com"
  REACT_APP_ZEROPOOL_NETWORK = "polygon"
  REACT_APP_BUCKET_URL = "https://r2.zkbob.com"
  REACT_APP_SNARK_PARAMS_VERSION = "22022023"
  REACT_APP_RESTRICTED_COUNTRIES = "AE"
  REACT_APP_LOCK_TIMEOUT = "900000"
  # REACT_APP_RESTRICTED_COUNTRIES = "BY,CU,IR,IQ,CI,LR,KP,RU,SD,SY,US,ZW"

[context.staging.environment]
  REACT_APP_EXPLORER_ADDRESS_TEMPLATE = "https://sepolia.etherscan.io/address/%s"
  REACT_APP_EXPLORER_TX_TEMPLATE = "https://sepolia.etherscan.io/tx/%s"
  REACT_APP_EXPLORER_URL = "https://sepolia.etherscan.io"
  REACT_APP_NETWORK = "11155111"
  REACT_APP_CONTRACT_ADDRESS = "0x3bd088C19960A8B5d72E4e01847791BD0DD1C9E6"
  REACT_APP_TOKEN_ADDRESS = "0x2C74B18e2f84B78ac67428d0c7a9898515f0c46f"
  REACT_APP_RELAYER_URL = "https://relayer.thgkjlr.website/"
  REACT_APP_PROVER_URL = "https://prover-staging.thgkjlr.website/"
  REACT_APP_RPC_URL = "https://rpc.sepolia.org"
  REACT_APP_ZEROPOOL_NETWORK = "sepolia"
  REACT_APP_BUCKET_URL = "https://r2-staging.zkbob.com"
  REACT_APP_SNARK_PARAMS_VERSION = "20022023"
  REACT_APP_RESTRICTED_COUNTRIES = "AE"
  REACT_APP_KYC_STATUS_URL = "https://api-stage.knowyourcat.id/v1/%s/categories?category=BABTokenWeek"
  REACT_APP_KYC_HOMEPAGE_URL = "https://stage.knowyourcat.id/address/%s/BABTokenWeek"
  REACT_APP_LOCK_TIMEOUT = "300000"
  # REACT_APP_RESTRICTED_COUNTRIES = "BY,CU,IR,IQ,CI,LR,KP,RU,SD,SY,US,ZW"

[context.goerli.environment]
  REACT_APP_EXPLORER_ADDRESS_TEMPLATE = "https://goerli.etherscan.io/address/%s"
  REACT_APP_EXPLORER_TX_TEMPLATE = "https://goerli.etherscan.io/tx/%s"
  REACT_APP_EXPLORER_URL = "https://goerli.etherscan.io"
  REACT_APP_NETWORK = "5"
  REACT_APP_CONTRACT_ADDRESS = "0x49661694a71B3Dab9F25E86D5df2809B170c56E6"
  REACT_APP_TOKEN_ADDRESS = "0x97a4ab97028466FE67F18A6cd67559BAABE391b8"
  REACT_APP_RELAYER_URL = "https://dev-relayer.thgkjlr.website/"
  REACT_APP_RPC_URL = "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
  REACT_APP_ZEROPOOL_NETWORK = "goerli"
  REACT_APP_BUCKET_URL = "https://r2-goerli.zkbob.com"
  REACT_APP_RESTRICTED_COUNTRIES = "AE"
  REACT_APP_LOCK_TIMEOUT = "300000"

[context.optimism.environment]
  REACT_APP_EXPLORER_ADDRESS_TEMPLATE = "https://optimistic.etherscan.io/address/%s"
  REACT_APP_EXPLORER_TX_TEMPLATE = "https://optimistic.etherscan.io/tx/%s"
  REACT_APP_EXPLORER_URL = "https://optimistic.etherscan.io"
  REACT_APP_NETWORK = "10"
  REACT_APP_CONTRACT_ADDRESS = "0x1CA8C2B9B20E18e86d5b9a72370fC6c91814c97C"
  REACT_APP_TOKEN_ADDRESS = "0xB0B195aEFA3650A6908f15CdaC7D92F8a5791B0B"
  REACT_APP_RELAYER_URL = "https://relayer-optimism.zkbob.com/"
  REACT_APP_RPC_URL = "https://mainnet.optimism.io"
  REACT_APP_ZEROPOOL_NETWORK = "optimism"
  REACT_APP_BUCKET_URL = "https://r2.zkbob.com"
  REACT_APP_SNARK_PARAMS_VERSION = "22022023"
  REACT_APP_RESTRICTED_COUNTRIES = "AE"
  REACT_APP_LOCK_TIMEOUT = "300000"
